#!/bin/sh

getDate()
{
	echo "$(date "+%a %m-%d-%y %T")"
}

getAudio()
{
	STATUS=$(amixer sget Master | tail -n1 | sed -r "s/.*\[(.*)\]/\1/")
	VOL=$(amixer get Master | tail -n1 | sed -r "s/.*\[(.*)%\].*/\1/")

	if [ "$STATUS" = "off" ]; then
    	echo "Mute"
    else
		echo "Vol: $VOL%"
    fi
}

getKB()
{
	#echo "$(setxkbmap -query | awk '/layout/{print $2}')"
	echo "$(xkb-switch -p)"
}

getVPN()
{
	VPN=$(nmcli -a | grep 'VPN connection' | sed -e 's/\( VPN connection\)*$//g')
	if [ "$VPN" != "" ]; then
		echo " VPN: $VPN |"
	fi
}

getNetwork()
{
	CONNAME=$(nmcli -t -f NAME,TYPE connection show --active | grep ethernet | cut -d ":" -f1)
	OPENVPN=$(nmcli -t -f NAME,TYPE connection show --active | grep 'vpn' | cut -d ":" -f1)
	WGVPN=$(nmcli -t -f NAME,TYPE connection show --active | grep 'wireguard' | cut -d ":" -f1)
	if [ -n "$CONNAME" ]; then
		if [ -n "$OPENVPN" ]; then
			echo "VPN: $OPENVPN | "
		elif [ -n "$WGVPN" ]; then
			echo "VPN: $WGVPN | "
		fi
	else
		echo "Offline | "
	fi
}

getBattery()
{
	BATCHARGE=$(cat /sys/class/power_supply/BAT0/capacity)
	echo "Bat: $BATCHARGE%"
}

getRAM()
{
	USEDRAM=$(free -h | sed '0,/ /s/ /X/' | awk 'NR==2{print $3}')
	TOTALRAM=$(free -h | sed '0,/ /s/ /X/' | awk 'NR==2{print $2}')
	RAMUSAGE="$USEDRAM/$TOTALRAM"
	USEDSWAP=$(free -h | sed '0,/ /s/ /X/' | awk 'NR==3{print $3}')
	TOTALSWAP=$(free -h | sed '0,/ /s/ /X/' | awk 'NR==3{print $2}')
	SWAPUSAGE="$USEDSWAP/$TOTALSWAP"

	if [ "$USEDSWAP" = "0B" ] || [ "$USEDSWAP" = "0.0Ki" ]; then
		echo "RAM: $RAMUSAGE"
	else
		echo "RAM: $RAMUSAGE | SWAP: $SWAPUSAGE"
	fi
}

getBrightness()
{
	CURRENTBRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/brightness)
	MAXBRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/max_brightness)
	BRIGHTPERCENT=$(($CURRENTBRIGHTNESS*100/$MAXBRIGHTNESS))
	echo "BRT: $BRIGHTPERCENT%"
}

parallelize()
{
	while true
	do
		sleep 2
	done
}
#parallelize &

while true
do
	xsetroot -name " $(getKB) | $(getAudio) | $(getRAM) | $(getNetwork)$(getDate)"
	sleep 0.5
done
